disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_whitespace
  - type_name

opt_in_rules: # some rules are only opt-in
  - empty_count
  - missing_docs
  - force_cast
  - force_try

included: # paths to include during linting. `--path` is ignored if present.
  - Sources
  - Tests

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - fastlane
  - Scripts

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
line_length:
  warning: 120
  error: 200

type_name:
  min_length: 3 # only warning
  max_length:
    warning: 40
    error: 50

identifier_name:
  min_length: 3 # only warning
  max_length:
    warning: 40
    error: 50

# reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
reporter: "xcode"
